export const FETCH_PRODUCTS_START = 'products/FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS =
  'products/FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'products/FETCH_PRODUCTS_ERROR';

export const DELETE_PRODUCT_START = 'products/DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS =
  'products/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'products/DELETE_PRODUCT_ERROR';
