export const FETCH_PRODUCTS_START = 'products/FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS =
  'products/FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'products/FETCH_PRODUCTS_ERROR';

export const FETCH_PRODUCT_START = 'products/FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'products/FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'products/FETCH_PRODUCT_ERROR';

export const DELETE_PRODUCT_START = 'products/DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS =
  'products/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'products/DELETE_PRODUCT_ERROR';

export const UPDATE_PRODUCT_START = 'products/UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_SUCCESS =
  'products/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'products/UPDATE_PRODUCT_ERROR';

export const CREATE_PRODUCT_START = 'products/CREATE_PRODUCT_START';
export const CREATE_PRODUCT_SUCCESS =
  'products/CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'products/CREATE_PRODUCT_ERROR';

// export const CREATE_NEW_ITEM_BOOL_START =
//   'products/CREATE_NEW_ITEM_BOOL_START';
// export const CREATE_NEW_ITEM_BOOL_SUCCESS =
//   'products/CREATE_NEW_ITEM_BOOL_SUCCESS';
// export const CREATE_NEW_ITEM_BOOL_ERROR =
//   'products/CREATE_NEW_ITEM_BOOL_ERROR';
